server:
  port: 7901
  error:
    include-message: always  # to see error message wrote in our exception when it is thrown
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trainingcode
    username: trainingcode
    password: trainingcode
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
